apiVersion: v1
kind: Service
metadata:
  name: it-company-service
spec:
  selector:
    app: it-company
  ports:
    - protocol: "TCP"
      port: 8080 # Внутренний порт
      targetPort: 8081 # Подключение к внешнему порту
  type: NodePort