create table companies
(
    id              int8 generated by default as identity,
    company_country varchar(255),
    company_name    varchar(255),
    primary key (id)
);

create table developers
(
    id         int8 generated by default as identity,
    first_name varchar(255),
    last_name  varchar(255),
    company_fk int8,
    primary key (id)
);

create table projects
(
    id                 int8 generated by default as identity,
    project_difficulty varchar(255),
    project_name       varchar(255),
    primary key (id)
);

create table projects_developers
(
    project_fk   int8 not null,
    developer_fk int8 not null
);

alter table if exists developers
    add constraint FKi1uplrqlii42gpng19q5rjdtu foreign key (company_fk) references companies;

alter table if exists projects_developers
    add constraint FKc56mi1oqbbdgycwdtwstxxfci foreign key (developer_fk) references developers;

alter table if exists projects_developers
    add constraint FKkjwomfqyrwd1ixf3wu5krmoag foreign key (project_fk) references projects;
